# Generated by Django 5.0 on 2024-02-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_code',
        ),
    ]
